package orchestrator

import (
	"fmt"
	"os"
	"path/filepath"
)

// DefaultDockerfile generates a Dockerfile for cure agent containers.
// It installs cure and the claude CLI into the devcontainer base image.
const defaultDockerfileTemplate = `# Generated by cure — agent container
ARG BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu
FROM ${BASE_IMAGE}

# Install cure CLI
COPY cure /usr/local/bin/cure
RUN chmod +x /usr/local/bin/cure

# Install Claude Code CLI (Node.js required)
RUN if command -v node >/dev/null 2>&1; then \
      npm install -g @anthropic-ai/claude-code 2>/dev/null || true; \
    fi

# Working directory
WORKDIR /workspace

# Default: start MCP server
CMD ["cure", "mcp", "serve", "--http", ":9100"]
`

// GenerateDockerfile writes the agent Dockerfile to the given directory.
// It also copies the current cure binary into the build context.
func GenerateDockerfile(dir string, baseImage string) error {
	if baseImage == "" {
		baseImage = "mcr.microsoft.com/devcontainers/base:ubuntu"
	}

	content := fmt.Sprintf(`# Generated by cure — agent container
FROM %s

# Install cure CLI
COPY cure /usr/local/bin/cure
RUN chmod +x /usr/local/bin/cure

# Working directory
WORKDIR /workspace

# Default: start MCP server
CMD ["cure", "mcp", "serve", "--http", ":9100"]
`, baseImage)

	dockerfilePath := filepath.Join(dir, "Dockerfile.cure")
	if err := os.WriteFile(dockerfilePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("orchestrator: write Dockerfile: %w", err)
	}

	// Copy current cure binary to build context
	cureBin, err := os.Executable()
	if err != nil {
		return fmt.Errorf("orchestrator: find cure binary: %w", err)
	}
	data, err := os.ReadFile(cureBin)
	if err != nil {
		return fmt.Errorf("orchestrator: read cure binary: %w", err)
	}
	destBin := filepath.Join(dir, "cure")
	if err := os.WriteFile(destBin, data, 0755); err != nil {
		return fmt.Errorf("orchestrator: copy cure binary: %w", err)
	}

	return nil
}
