// Package orchestrator manages the lifecycle of agent containers via Docker Compose.
// It generates compose files from devcontainer.json and coordinates MCP connections.
package orchestrator

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mrlm-net/cure/pkg/mcp"
	"github.com/mrlm-net/cure/pkg/project"
)

// ContainerStatus represents the health of an orchestrated container.
type ContainerStatus struct {
	Name    string `json:"name"`
	State   string `json:"state"`
	Health  string `json:"health"`
	MCPPort int    `json:"mcp_port"`
}

// Orchestrator manages the lifecycle of agent containers.
type Orchestrator struct {
	project    *project.Project
	composeDir string
	secret     string
	basePort   int
	agentCount int
}

// New creates an Orchestrator for the given project.
func New(p *project.Project, composeDir string) *Orchestrator {
	agentCount := 4
	if p.Defaults.MaxAgents > 0 {
		agentCount = p.Defaults.MaxAgents
	}
	return &Orchestrator{
		project:    p,
		composeDir: composeDir,
		basePort:   9100,
		agentCount: agentCount,
	}
}

// Init generates docker-compose.cure.yml and Dockerfile.cure from the project config.
func (o *Orchestrator) Init() error {
	secret, err := generateSecret()
	if err != nil {
		return fmt.Errorf("orchestrator: generate secret: %w", err)
	}
	o.secret = secret

	// Generate agent Dockerfile with cure binary baked in
	baseImage := "mcr.microsoft.com/devcontainers/base:ubuntu"
	if o.project.Devcontainer != nil && o.project.Devcontainer.Image != "" {
		baseImage = o.project.Devcontainer.Image
	}
	if err := GenerateDockerfile(o.composeDir, baseImage); err != nil {
		return err
	}

	compose := o.generateCompose()

	path := filepath.Join(o.composeDir, "docker-compose.cure.yml")
	return os.WriteFile(path, []byte(compose), 0644)
}

// Up starts all agent containers.
func (o *Orchestrator) Up(ctx context.Context) error {
	return o.compose(ctx, nil, "up", "-d")
}

// Down stops all agent containers.
func (o *Orchestrator) Down(ctx context.Context) error {
	return o.compose(ctx, nil, "down")
}

// Status returns the health status of all containers.
func (o *Orchestrator) Status(ctx context.Context) ([]ContainerStatus, error) {
	cmd := exec.CommandContext(ctx, "docker", "compose", "-f",
		filepath.Join(o.composeDir, "docker-compose.cure.yml"),
		"ps", "--format", "json")
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("orchestrator: status: %w", err)
	}

	var statuses []ContainerStatus
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line == "" {
			continue
		}
		var raw struct {
			Name  string `json:"Name"`
			State string `json:"State"`
		}
		if json.Unmarshal([]byte(line), &raw) == nil {
			statuses = append(statuses, ContainerStatus{
				Name:  raw.Name,
				State: raw.State,
			})
		}
	}
	return statuses, nil
}

// Logs streams logs from a specific container.
func (o *Orchestrator) Logs(ctx context.Context, name string, w io.Writer) error {
	cmd := exec.CommandContext(ctx, "docker", "compose", "-f",
		filepath.Join(o.composeDir, "docker-compose.cure.yml"),
		"logs", "-f", name)
	cmd.Stdout = w
	cmd.Stderr = w
	return cmd.Run()
}

// MCPClient returns an MCP client for a specific agent container.
func (o *Orchestrator) MCPClient(agentIndex int) *mcp.Client {
	port := o.basePort + agentIndex + 1
	endpoint := fmt.Sprintf("http://127.0.0.1:%d/mcp", port)
	return mcp.NewClient(endpoint, mcp.WithBearerToken(o.secret))
}

func (o *Orchestrator) compose(ctx context.Context, w io.Writer, args ...string) error {
	allArgs := append([]string{"compose", "-f",
		filepath.Join(o.composeDir, "docker-compose.cure.yml")}, args...)
	cmd := exec.CommandContext(ctx, "docker", allArgs...)
	if w != nil {
		cmd.Stdout = w
		cmd.Stderr = w
	}
	return cmd.Run()
}

func (o *Orchestrator) generateCompose() string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by cure — do not edit manually")
	fmt.Fprintln(&b, "services:")

	for i := 0; i < o.agentCount; i++ {
		name := fmt.Sprintf("agent-%d", i+1)
		hostPort := o.basePort + i + 1

		fmt.Fprintf(&b, "  %s:\n", name)
		fmt.Fprintln(&b, "    build:")
		fmt.Fprintln(&b, "      context: .")
		fmt.Fprintln(&b, "      dockerfile: Dockerfile.cure")
		cureBin, _ := os.Executable()
		fmt.Fprintln(&b, "    volumes:")
		fmt.Fprintln(&b, "      - .:/workspace:cached")
		fmt.Fprintf(&b, "      - %s:/usr/local/bin/cure:ro\n", cureBin)
		fmt.Fprintln(&b, "    working_dir: /workspace")
		fmt.Fprintln(&b, "    environment:")
		fmt.Fprintf(&b, "      - CURE_AGENT_NAME=%s\n", name)
		fmt.Fprintf(&b, "      - CURE_MCP_PORT=%d\n", o.basePort)
		fmt.Fprintf(&b, "      - CURE_MCP_SECRET=%s\n", o.secret)
		fmt.Fprintf(&b, "      - CURE_HOST_URL=http://host.docker.internal:${CURE_GUI_PORT:-9998}\n")
		fmt.Fprintln(&b, "    ports:")
		fmt.Fprintf(&b, "      - \"%d:%d\"\n", hostPort, o.basePort)
		fmt.Fprintf(&b, "    command: [\"cure\", \"mcp\", \"serve\", \"--http\", \":%d\"]\n", o.basePort)
		fmt.Fprintln(&b, "    networks:")
		fmt.Fprintln(&b, "      - cure-net")
	}

	fmt.Fprintln(&b, "\nnetworks:")
	fmt.Fprintln(&b, "  cure-net:")
	fmt.Fprintln(&b, "    driver: bridge")
	return b.String()
}

func generateSecret() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
