package generate

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mrlm-net/cure/pkg/fs"
	"github.com/mrlm-net/cure/pkg/prompt"
	"github.com/mrlm-net/cure/pkg/terminal"
)

// GitignoreOpts configures the behaviour of [GenerateGitignore].
type GitignoreOpts struct {
	// Profiles is the list of profile keys to include (e.g. "go", "node").
	// An empty slice means only the universal section is generated.
	Profiles []string

	// OutputPath is the destination file. Defaults to "./.gitignore".
	OutputPath string

	// Force overwrites an existing file without prompting.
	Force bool

	// DryRun writes the rendered output to w and returns without touching disk.
	DryRun bool

	// NonInteractive skips prompts and derives all values from Profiles.
	NonInteractive bool
}

// gitignoreSection holds a section header and its deduplicated pattern lines.
type gitignoreSection struct {
	Header   string
	Patterns []string
}

// GenerateGitignore builds a .gitignore from the requested profiles and writes it
// to OutputPath (or w when DryRun is set). The function:
//  1. Validates that all requested profile keys are known.
//  2. Builds a universal section that is always present.
//  3. Appends one section per requested profile in gitignoreProfileOrder order.
//  4. Deduplicates patterns across all sections; comment lines (starting with #)
//     are never deduplicated so each section keeps its header comment.
//  5. In dry-run mode, writes rendered content to w and returns nil.
//  6. Otherwise checks for existing file / force flag, then atomically writes.
func GenerateGitignore(ctx context.Context, w io.Writer, opts GitignoreOpts) error {
	if opts.OutputPath == "" {
		opts.OutputPath = "./.gitignore"
	}

	// Validate all requested profile keys before doing any work.
	for _, key := range opts.Profiles {
		if _, ok := gitignoreProfiles[key]; !ok {
			return fmt.Errorf("unknown gitignore profile %q; valid profiles: %s",
				key, strings.Join(gitignoreProfileOrder, ", "))
		}
	}

	// Build the set of requested profile keys for quick lookup.
	requested := make(map[string]bool, len(opts.Profiles))
	for _, key := range opts.Profiles {
		requested[key] = true
	}

	// seen tracks every non-comment pattern that has already been emitted so
	// that duplicates across sections are silently dropped.
	seen := make(map[string]struct{})

	// dedup filters patterns for a section. Comment lines (# …) are always
	// emitted as-is; data lines are emitted only once across all sections.
	dedup := func(patterns []string) []string {
		out := make([]string, 0, len(patterns))
		for _, p := range patterns {
			if strings.HasPrefix(p, "#") {
				// Section header comments are always kept.
				out = append(out, p)
				continue
			}
			if _, already := seen[p]; already {
				continue
			}
			seen[p] = struct{}{}
			out = append(out, p)
		}
		return out
	}

	// Universal section is always the first section.
	sections := []gitignoreSection{
		{
			Header:   "# Universal",
			Patterns: dedup(universalPatterns[1:]), // skip the leading "# Universal" comment
		},
	}

	// Append profile sections in canonical order.
	for _, key := range gitignoreProfileOrder {
		if !requested[key] {
			continue
		}
		entry := gitignoreProfiles[key]
		filtered := dedup(entry.Patterns)
		if len(filtered) == 0 {
			continue
		}
		// First pattern of each profile is always a comment header; use it as the
		// section Header field and pass the remainder as Patterns.
		header := "# " + entry.Label
		body := filtered
		if len(filtered) > 0 && strings.HasPrefix(filtered[0], "#") {
			header = filtered[0]
			body = filtered[1:]
		}
		sections = append(sections, gitignoreSection{
			Header:   header,
			Patterns: body,
		})
	}

	// Build the output directly with a strings.Builder — simpler and faster
	// than going through the template registry for plain text output.
	var sb strings.Builder
	sb.WriteString("# Generated by cure generate gitignore\n")
	sb.WriteString("# https://github.com/mrlm-net/cure\n")
	for _, sec := range sections {
		sb.WriteString("\n")
		sb.WriteString(sec.Header)
		sb.WriteString("\n")
		for _, p := range sec.Patterns {
			sb.WriteString(p)
			sb.WriteString("\n")
		}
	}
	output := sb.String()

	if opts.DryRun {
		fmt.Fprintf(w, "# Dry run mode: would write to %s\n\n", opts.OutputPath)
		_, err := fmt.Fprint(w, output)
		return err
	}

	// Check for existing file.
	exists, err := fs.Exists(opts.OutputPath)
	if err != nil {
		return fmt.Errorf("failed to check if %s exists: %w", opts.OutputPath, err)
	}
	if exists && !opts.Force {
		return fmt.Errorf("%s already exists; use --force to overwrite", opts.OutputPath)
	}

	if err := fs.AtomicWrite(opts.OutputPath, []byte(output), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", opts.OutputPath, err)
	}

	return nil
}

// GitignoreCommand implements [terminal.Command] for `cure generate gitignore`.
type GitignoreCommand struct {
	nonInteractive bool
	force          bool
	dryRun         bool
	profiles       string // comma-separated profile keys (non-interactive)
	outputPath     string
}

// Name returns the subcommand name.
func (c *GitignoreCommand) Name() string { return "gitignore" }

// Description returns a short description for the help listing.
func (c *GitignoreCommand) Description() string {
	return "Generate .gitignore with embedded language and tool patterns"
}

// Usage returns detailed usage information.
func (c *GitignoreCommand) Usage() string {
	return `Usage: cure generate gitignore [flags]

Generate a .gitignore file with embedded canonical patterns for popular
languages, runtimes, operating systems, and editors.

Interactive mode (default):
  cure generate gitignore

Non-interactive mode (for CI/CD):
  cure generate gitignore --non-interactive --profiles go,node,macos

Available profiles:
  go         Go binaries, test output, vendor/
  node       node_modules, npm/yarn debug logs, dist/, build/
  python     __pycache__, *.pyc, venv, .pytest_cache
  rust       debug/, target/, Cargo.lock
  java       *.class, *.jar, *.war
  macos      .DS_Store, Spotlight, Trashes
  windows    Thumbs.db, desktop.ini, $RECYCLE.BIN
  linux      *~, .fuse_hidden*, .Trash-*
  jetbrains  .idea/, *.iml
  vscode     .vscode/*, .history/
  vim        *.swp, *.swo, Emacs lock files

Flags:
  --non-interactive   Disable prompts; use --profiles to select profiles
  --dry-run           Preview generated output without writing to disk
  --profiles          Comma-separated profile keys (non-interactive mode)
  --output            Output file path (default: ./.gitignore)
  --force             Overwrite existing file without prompting

Examples:
  # Interactive MultiSelect menu
  cure generate gitignore

  # Non-interactive: Go + Node.js + macOS profiles
  cure generate gitignore --non-interactive --profiles go,node,macos

  # Preview only (no file written)
  cure generate gitignore --non-interactive --profiles go --dry-run

  # Overwrite existing .gitignore
  cure generate gitignore --non-interactive --profiles go --force
`
}

// Flags defines the flag set for GitignoreCommand.
func (c *GitignoreCommand) Flags() *flag.FlagSet {
	fset := flag.NewFlagSet("gitignore", flag.ContinueOnError)
	fset.BoolVar(&c.nonInteractive, "non-interactive", false, "Disable prompts, use --profiles to select")
	fset.BoolVar(&c.force, "force", false, "Overwrite existing file without prompting")
	fset.BoolVar(&c.dryRun, "dry-run", false, "Preview output without writing file")
	fset.StringVar(&c.profiles, "profiles", "", "Comma-separated profile keys")
	fset.StringVar(&c.outputPath, "output", "./.gitignore", "Output file path")
	return fset
}

// Run executes the gitignore generation command.
func (c *GitignoreCommand) Run(ctx context.Context, tc *terminal.Context) error {
	profileKeys, err := c.resolveProfiles(tc)
	if err != nil {
		return err
	}

	opts := GitignoreOpts{
		Profiles:       profileKeys,
		OutputPath:     c.outputPath,
		Force:          c.force,
		DryRun:         c.dryRun,
		NonInteractive: c.nonInteractive,
	}

	if err := GenerateGitignore(ctx, tc.Stdout, opts); err != nil {
		return err
	}

	if !c.dryRun {
		c.printSuccess(tc)
	}
	return nil
}

// resolveProfiles returns the list of profile keys to include.
// In non-interactive mode it parses --profiles; in interactive mode it presents
// a MultiSelect menu unless stdout is not a terminal.
func (c *GitignoreCommand) resolveProfiles(tc *terminal.Context) ([]string, error) {
	if c.nonInteractive {
		return parseProfileFlag(c.profiles)
	}

	// When stdin is not interactive (pipe, redirect, test buffer), fall back to
	// non-interactive without profiles (universal section only).
	if !prompt.IsInteractive(os.Stdin) {
		return parseProfileFlag(c.profiles)
	}

	// Build MultiSelect options in canonical order.
	options := make([]prompt.Option, 0, len(gitignoreProfileOrder))
	for _, key := range gitignoreProfileOrder {
		entry := gitignoreProfiles[key]
		options = append(options, prompt.Option{
			Label: entry.Label,
			Value: key,
		})
	}

	prompter := prompt.NewPrompter(tc.Stdout, os.Stdin)
	selected, err := prompter.MultiSelect("Select .gitignore profiles", options)
	if err != nil {
		return nil, err
	}

	keys := make([]string, 0, len(selected))
	for _, opt := range selected {
		keys = append(keys, opt.Value)
	}
	return keys, nil
}

// parseProfileFlag splits a comma-separated profile string into a validated
// slice of profile keys. An empty string returns an empty (non-nil) slice.
// Unknown keys return an error before any slice is returned.
func parseProfileFlag(raw string) ([]string, error) {
	if raw == "" {
		return []string{}, nil
	}
	parts := strings.Split(raw, ",")
	keys := make([]string, 0, len(parts))
	for _, p := range parts {
		key := strings.TrimSpace(p)
		if key == "" {
			continue
		}
		if _, ok := gitignoreProfiles[key]; !ok {
			return nil, fmt.Errorf("unknown gitignore profile %q; valid profiles: %s",
				key, strings.Join(gitignoreProfileOrder, ", "))
		}
		keys = append(keys, key)
	}
	return keys, nil
}

// printSuccess writes the post-generation summary to tc.Stdout.
func (c *GitignoreCommand) printSuccess(tc *terminal.Context) {
	relPath, _ := filepath.Rel(".", c.outputPath)
	if relPath == "" {
		relPath = c.outputPath
	}
	fmt.Fprintf(tc.Stdout, "Generated %s successfully.\n\n", relPath)
	fmt.Fprintln(tc.Stdout, "Next steps:")
	fmt.Fprintln(tc.Stdout, "1. Review .gitignore and add project-specific paths as needed")
	fmt.Fprintln(tc.Stdout, "2. Commit to version control (git add .gitignore && git commit -m \"Add .gitignore\")")
}
